name: Tests
on: [push]

jobs:
  test_archiver:
    runs-on: ubuntu-latest
    name: A job to test the archiver
    steps:
    - name: Prepare some files
      run: |
        touch file1
        mkdir dir1
        cd dir1
        touch file2
        cd ..
    - name: Archive single file
      uses: AssassinTee/archiver-action@dev
      with:
        archiver: zip
        name: output.zip
        files: |
          file1
    - name: Archive directory
      uses: AssassinTee/archiver-action@dev
      with:
        archiver: zip
        name: output2.zip
        files: |
          dir1
    - name: Archive files and directories
      uses: AssassinTee/archiver-action@dev
      with:
        archiver: zip
        name: output3.zip
        files: |
          file1
          dir1
    - name: Show Directory
      run: |
        ls -l
    - uses: actions/upload-artifact@master
      with:
        name: out1
        path: output.zip
    - uses: actions/upload-artifact@master
      with:
        name: out2
        path: output2.zip
    - uses: actions/upload-artifact@master
      with:
        name: out3
        path: output3.zip
